### PR TITLE
Comma fix in `MySkin.xaml.vb` code

### PR DESCRIPTION
**Pull request by 3gf8jv4dv**
I do not know why no one noticed it, and the compilation was successful… In order to maintain a consistent style and avoid potential problems, this PR was opened.

**RELATED:**
- #3885
- #4138

### CODE REVIEW

**Comment by JingHai-Lingyun** [comment]
Comma?

**Comment by allMagicNB** [comment]
@wuyuncheng-26 出来挨打

**Comment by Pigeon0v0** [comment]
#破坏性改动

**Comment by SALTWOOD** [comment]
so why the compilation was successful... strange

**Comment by LTCatt** [comment]
Visual Studio supports both `,` and `，`

**Comment by wuyuncheng-26** [comment]
> @wuyuncheng-26 出来挨打（

过于难绷（

**Comment by wuyuncheng-26** [comment]
> I do not know why no one noticed it, and the compilation was successful… In order to maintain a consistent style and avoid potential problems, this PR was opened.
> 
> **RELATED:**
> 
> * [添加 Follower's Cape 的翻译 #3885](https://github.com/Hex-Dragon/PCL2/pull/3885)
> * [修复追随者披风不能被汉化的 bug #4138](https://github.com/Hex-Dragon/PCL2/pull/4138)

Thanks for fixing it! ~~We didn't spot this problem~~

**Comment by wuyuncheng-26** [comment]
> Visual Studio supports both `,` and `，`

Yeah

**Pull request merged**
